# Generated by Django 3.2 on 2022-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_message',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact_message',
            name='message',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
