# Generated by Django 3.2 on 2022-06-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='Product_Review',
        ),
    ]
